FROM opendronemap/nodeodm:latest

RUN /code/venv/bin/pip install --no-cache-dir numpy==1.26.4 && \
    cp /usr/lib/python3/dist-packages/osgeo/_gdal_array.cpython-312-x86_64-linux-gnu.so /code/venv/lib/python3.12/site-packages/osgeo/
